# Site settings
title: Colter Studios
description:  Collections

baseurl: # the subpath of your site, e.g. /blog
basedir: /

assets:
  img: assets/img
  favicon: assets/favicon

url: "https://www.colterstudios.com" # the base hostname & protocol for your site

plugins:
  - octopress-debugger
  
email: connie@colterstudios.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
