# Site settings
title: Colter Studios
email: connie@colterstudios.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of Pacific Nothwest artist Connie Colter's sculptures and ceramics. 
baseurl: "/urban-theme" # the subpath of your site, e.g. /blog
url: "http://www.colterstudios.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
